### ISSUE TITLE
Works on Chromebook but with error messages in terminal output

### ISSUE THREAD

**Issue by xpat** [googlecodelabs/flutter-github-graphql-client#4]
Thanks for the codelab.  I got it to work on my Chromebook.  I added " gdk_set_allowed_backends("x11");" to the linux main.cc (see github issue #57932). 

Just wanted to report some output from my terminal when using the desktop app. 

`[30897:30999:0714/224556.039224:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[30897:30999:0714/224556.040362:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[30897:30999:0714/224556.041202:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[30897:30897:0714/224557.153617:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 1 times!
[30897:30897:0714/224557.185157:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 2 times!
[30897:30897:0714/224557.232237:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 3 times!
[31532:31532:0714/224617.732448:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
Opening in existing browser session.
[0714/224617.869794:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

`

**Comment by maks** [comment]
Good news is that current Flutter master channel now has the `gdk_set_allowed_backends("x11");` line when you create main.cc using `flutter create`.

Also I'm not seeing these error messages using: `Flutter (Channel master, 1.21.0-6.0.pre.17, on Linux, locale en_US.UTF-8)` so maybe this has now also been fixed in master?

**Comment by xpat** [comment]
@maks  It's definitely nice to not have to manually add that for each new project.  (Now I only hope that I'll remember to remove it once Wayland is the standard.)

As for error messages, I'm still getting them.  Once I've authenticated, every time I use the app my terminal fills with error messages.  They don't necessarily trip me up.  Since this is a codelab, I just mention it for the record.  So I'm going to close this issue.  If you think the errors are important let me know and I'll see where else I can report them.  

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

• No issues found!

[10004:10004:0726/141043.674730:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
[10042:10075:0726/141044.748045:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.808116:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.808527:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.808841:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.809145:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.809571:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.815242:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.816341:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.817007:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.818158:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.818821:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.821570:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.823531:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.824142:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.826845:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.859846:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.860100:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.860376:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.860596:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.860807:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.860997:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.861207:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.861421:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.861632:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.861856:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.862063:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.862269:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.862467:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.862741:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.863425:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.863622:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10042:10075:0726/141044.863848:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10004:10117:0726/141045.243647:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[10004:10117:0726/141045.243968:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[10004:10117:0726/141045.244185:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[10042:10042:0726/141046.306044:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 1 times!
[10042:10042:0726/141046.354762:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 2 times!
[10042:10042:0726/141046.372026:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 3 times!
[0726/141049.777455:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
[10394:10394:0726/141059.406402:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id
[10394:10478:0726/141100.005871:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[10394:10478:0726/141100.006130:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[10394:10478:0726/141100.011552:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
[10430:10498:0726/141100.251393:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.252749:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.253901:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.255327:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.255874:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.256125:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.256994:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.257898:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.258397:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.259765:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.262177:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.262535:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.262846:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.263154:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.263476:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.265604:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.266225:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.266728:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.267581:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.268260:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.268583:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.268957:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.269221:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.269496:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.269902:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.270239:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.270537:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.270821:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.271208:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.272021:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.272341:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10498:0726/141100.272634:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: No such file or directory (2)
[10430:10430:0726/141101.358736:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 1 times!
[10430:10430:0726/141101.421979:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 2 times!
[10430:10430:0726/141101.529272:ERROR:gl_surface_presentation_helper.cc(258)] GetVSyncParametersIfAvailable() failed for 3 times!
